### ISSUE TITLE
Refactor expensive Marshals into unsafe calls

### ISSUE THREAD

**Issue by sr229** [vignetteapp/Oxide#2]
No matter how much we try optimizing, the bottleneck with this implementation is using `Marshal`, which is awfully expensive. The only way to get the library in a performant state is using `unsafe` - but this will require memory management manually (which we do anyway). 

Consider how much experience we have dealing with unsafe code in C#, we can leverage the performance from that by refactoring every Marshal code into an unsafe call.

**Comment by LeNitrous** [comment]
Closed with https://github.com/vignetteapp/Oxide/commit/8a3b676c0c1b88ceaed1d1391693f0f21e6031e2

**Comment by SupinePandora43** [comment]
There's still **a lot** of `[MarshalAs]` and heap allocation going on

**Comment by sr229** [comment]
> There's still **a lot** of `[MarshalAs]` and heap allocation going on

We're putting Oxide's development on indefinite hold for now, so we won't be working on this for a while. You're free to open a PR if you wish to.
